[project]
name = "ctdashboards"
version = "0.1.0"
description = "grafana dashboard course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "pytest>=8.3.5",
    "ruff>=0.11.6",
]
